src/blog/urls.py
from django.contrib import admin
from django.urls import include, path
from blog import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('posts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.urls import path
from posts.views import BlogHome, BlogPostCreate, BlogPostUpdate, BlogPostDetail, BlogPostDelete

app_name = 'posts'

urlpatterns = [
    path('', BlogHome.as_view(), name = 'home'),
    path('create/', BlogPostCreate.as_view(), name = 'create'),
    path('<str:slug>/',BlogPostDetail.as_view(), name = 'post'),
    path('edit/<str:slug>/', BlogPostUpdate.as_view(), name = 'edit'),
    path('delete/<str:slug>/', BlogPostDelete.as_view(), name = 'delete'),



    
]

src/posts/models.py
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.db import models
from django.urls import reverse


User = get_user_model()

class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name="Titre")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete= models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name= 'Publié')
    content = models.TextField(blank=True, verbose_name='Contenu')
    thumbnail = models.ImageField(blank=True, upload_to='blog')
    
    class Meta :
        ordering = ["-created_on"]
        verbose_name = 'Article'

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug :
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    
    @property
    def author_or_default(self):
        if self.author:
            return self.author.username
        return 'Auteur inconnu'
    
    def get_absolute_url(self):
        return reverse('posts:home')
    

src/posts/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from posts.models import BlogPost
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator



# Create your views here.

class BlogHome(ListView):
    model = BlogPost
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset
        return queryset.filter(published=True)

@method_decorator(login_required, name ='dispatch')
class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = 'posts/blogpost_create.html'
    fields = ['title', 'content']

@method_decorator(login_required, name ='dispatch')
class BlogPostUpdate(UpdateView):
    model = BlogPost
    template_name = 'posts/blogpost_edit.html'
    fields = ['title', 'content', 'published', ]

class BlogPostDetail(DetailView):
    model = BlogPost
    template_name = 'posts/blogpost_detail.html'
    context_object_name = 'post'
    
@method_decorator(login_required, name ='dispatch')
class BlogPostDelete(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('posts:home')
    context_object_name = 'post'

    

src/posts/templates/posts/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block title %}

<title> Supprimer un article </title>
{% endblock title %}

{% block content %}



<form method="POST">
    {% csrf_token %}
    <p>Etes vous sûr de supprimer "{{ post.title }}"</p>
    
<input type = "submit" value = "Oui, supprimer"  class="btn btn-delete">
</form> 


{% endblock content %}

src/posts/templates/posts/blogpost_create.html
{% extends 'base.html' %}

{% block title %}
<title> Ajouter un article </title>
{% endblock title %}

{% block content %}
<h1> Ajouter un article </h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
<input type = "submit" value = "Créer"  class="btn btn-submit">
</form>    

{% endblock content%}

src/posts/templates/posts/blogpost_detail.html
{% extends 'base.html' %}

{% block title %}

<title> {{ post.title  }} </title>
{% endblock title %}

{% block content %}
<article class = "post-detail">

<h1> {{ post.title }}</h1>
<img src="{{ post.thumbnail.url }}" alt = "l'image de l'article">

<div> {{ post.content|linebreaks|safe }} </div>
</article>
{% endblock content %}

src/posts/templates/posts/blogpost_edit.html
{% extends 'base.html' %}

{% block title %}
<title> Modifier un article </title>
{% endblock title %}

{% block content %}
<h1> Modifier un article </h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
<input type = "submit" value = "Editer" class="btn btn-submit">
</form>    

{% endblock content%}

src/posts/templates/posts/blogpost_list.html
     {% extends 'base.html' %}  
       
     {% block title %}
       <title> Accueil du site </title>
       {% endblock title %}

     {% block content %}

<h1> le blog de Docstring </h1>

{% for post in posts %}
<article>
<div class="post-title">
    <h2> {{ post.title }} </h2>
    {% if request.user.is_authenticated %}
    <div>
     <a href = "{% url 'posts:edit' slug=post.slug %}">Editer</a>
     <a href = "{% url 'posts:delete' slug=post.slug %}">Supprimer</a>

    </div>

    {% endif %}
</div>



    <h5 class ="post-author"> Publié par <i> {{ post.author_or_default }}</i> le {{ post.created_on|date:'j F Y' }}</h5>
    <p class ="post-excerpt"> {{ post.content|safe|truncatewords:50 }} </p>
    <form action="{% url 'posts:post' slug=post.slug %}">
     <button class=" btn btn-submit"> Lire l'article</button>
    </form>
</article>
{% endfor %}

     
     {% endblock content %}

        

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<html>
    <head>
        <meta charset="utf-8">
        {% block title %}
        
        <title>Accueil du blog </title>
        {% endblock title %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        
    </head>
    
    <body>
        <nav>
            <a href="{% url 'posts:home' %}"> accueil</a>
            {% if request.user.is_authenticated %}
            <a href = "{% url 'posts:create' %}"> Ajouter un article </a>
            {% endif %}

        </nav>

        <section id = "blog">
            {% block content %}{% endblock content %} 
        </section>

        
    </body>
</html>